#!/usr/bin/env bun

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const packRoot = join(repoRoot, "assets", "packs", "facult-operating-model");
const codexPluginRoot = join(repoRoot, "plugins", "fclt");
const outputPath = join(repoRoot, "src", "builtin-assets.ts");
const includedTextExtensions = new Set([
  ".cjs",
  ".js",
  ".json",
  ".md",
  ".toml",
]);
const includedBinaryExtensions = new Set([".png"]);
const includedExtensions = new Set([
  ...includedTextExtensions,
  ...includedBinaryExtensions,
]);

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const pathValue = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walk(pathValue)));
      continue;
    }
    if (
      [...includedExtensions].some((extension) =>
        entry.name.endsWith(extension)
      )
    ) {
      files.push(pathValue);
    }
  }
  return files.sort();
}

async function readEntries(
  root: string,
  extensions: Set<string>,
  encoding: "base64" | "utf8"
): Promise<Record<string, string>> {
  const files = (await walk(root)).filter((file) =>
    [...extensions].some((extension) => file.endsWith(extension))
  );
  const entries: Record<string, string> = {};
  for (const file of files) {
    const key = relative(root, file).split("\\").join("/");
    entries[key] = await readFile(file, encoding);
  }
  return entries;
}

function singleQuotedStringLiteral(value: string): string {
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

const encodedPackEntries = singleQuotedStringLiteral(
  JSON.stringify(await readEntries(packRoot, includedTextExtensions, "utf8"))
);
const encodedPluginEntries = singleQuotedStringLiteral(
  JSON.stringify(
    await readEntries(codexPluginRoot, includedTextExtensions, "utf8")
  )
);
const encodedPluginBinaryEntries = singleQuotedStringLiteral(
  JSON.stringify(
    await readEntries(codexPluginRoot, includedBinaryExtensions, "base64")
  )
);
const body = `// Generated by scripts/generate-builtin-assets.ts. Do not edit by hand.

export const BUILTIN_OPERATING_MODEL_FILES = JSON.parse(
  // biome-ignore lint/suspicious/noTemplateCurlyInString: Built-in templates intentionally contain literal render placeholders.
  ${encodedPackEntries}
) as Record<string, string>;

export const BUILTIN_FCLT_CODEX_PLUGIN_FILES = JSON.parse(
  // biome-ignore lint/suspicious/noTemplateCurlyInString: Built-in plugin files intentionally contain literal render placeholders.
  ${encodedPluginEntries}
) as Record<string, string>;

export const BUILTIN_FCLT_CODEX_PLUGIN_BINARY_FILES = JSON.parse(
  ${encodedPluginBinaryEntries}
) as Record<string, string>;
`;

await writeFile(outputPath, body, "utf8");
