#!/usr/bin/env bun

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const packRoot = join(repoRoot, "assets", "packs", "facult-operating-model");
const outputPath = join(repoRoot, "src", "builtin-assets.ts");
const includedExtensions = new Set([".md", ".toml"]);

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const pathValue = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walk(pathValue)));
      continue;
    }
    if (
      [...includedExtensions].some((extension) =>
        entry.name.endsWith(extension)
      )
    ) {
      files.push(pathValue);
    }
  }
  return files.sort();
}

const files = await walk(packRoot);
const entries: Record<string, string> = {};
for (const file of files) {
  const key = relative(packRoot, file).split("\\").join("/");
  entries[key] = await readFile(file, "utf8");
}

function singleQuotedStringLiteral(value: string): string {
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

const encodedEntries = singleQuotedStringLiteral(JSON.stringify(entries));
const body = `// Generated by scripts/generate-builtin-assets.ts. Do not edit by hand.

export const BUILTIN_OPERATING_MODEL_FILES = JSON.parse(
  ${encodedEntries}
) as Record<string, string>;
`;

await writeFile(outputPath, body, "utf8");
