#!/bin/sh

set -eu

unset GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_CEILING_DIRECTORIES GIT_COMMON_DIR
unset GIT_CONFIG GIT_CONFIG_COUNT GIT_CONFIG_PARAMETERS GIT_CONFIG_SYSTEM
unset GIT_CONFIG_GLOBAL GIT_CONFIG_NOSYSTEM GIT_DIR GIT_DISCOVERY_ACROSS_FILESYSTEM
unset GIT_GRAFT_FILE GIT_IMPLICIT_WORK_TREE GIT_INDEX_FILE GIT_INTERNAL_SUPER_PREFIX
unset GIT_NAMESPACE GIT_NO_REPLACE_OBJECTS GIT_OBJECT_DIRECTORY GIT_PREFIX
unset GIT_QUARANTINE_PATH GIT_REPLACE_REF_BASE GIT_SHALLOW_FILE GIT_WORK_TREE

index=0
while [ "$index" -lt 64 ]; do
  key_name="GIT_CONFIG_KEY_$index"
  value_name="GIT_CONFIG_VALUE_$index"
  unset "$key_name" "$value_name"
  index=$((index + 1))
done

if [ "${1:-}" = "--ci" ]; then
  export FACULT_TEST_SKIP_LOCAL=1
  shift
fi

exec bun test "$@"
